### ISSUE TITLE
Possible to mark all retweets as seen?

### ISSUE THREAD

**Issue by Turbito** [Psycojoker/t2m#17]
I have a bot and I can mark all tweets as seen but I don't know if it's possible to mark retweets as seen as well for avoid its posting on mastodon...
I had tried it many ways but I don't get it...

Thanks in advance, very useful the tool!

**Comment by zoski** [comment]
Have you tried adding `-r` 
I didn't remember running into this problem. 

Regards

**Comment by Turbito** [comment]
yeah but no luck...
I tried it with `-r` the `one` and with the `all` options

**Comment by zoski** [comment]
Weird. I just looked at my command history and what I see is something like that:
`./t2m one twittAccount -m Account@mastodon.server.fr -r -o`
Have you tried that ? With the **-r** and **-o**.

If it's not working I'll add some bots to check that.

**Comment by Turbito** [comment]
yes, thats the one I tried.
If you please could check it..

**Comment by zoski** [comment]
Here is some news @Turbito 

I got no problem following the documentation. Here is what I did:
```Bash
# Adding the account in debug mode with '-d' a checking the last 10 tweets and retweets
./t2m one twitterAccount -m mastoAccount@masto.raildecake.fr -n 10 -r -d
# Forwarding the 5 last tweets and retweets with "-r"
./t2m one twitterAccount -m mastoAccount@masto.raildecake.fr -n 5 -r
# Marking all tweets and retweets as seen
./t2m one twitterAccount -m mastoAccount@masto.raildecake.fr -r -o
# Checking if everything is fine (and it was)
./t2m all -r
# Got a "Nothing to do for twitterAccount" 
```

**Comment by Turbito** [comment]
Maybe I didn't the debug thing?
Well thanks you for confirm I was my fault.

**Comment by zoski** [comment]
The debug step is optional... Good luck
